image:
  pullPolicy: IfNotPresent
  repository: directus/directus
  tag: latest
  imagePullSecrets: []
# Only set this to true if you are using a postgres database with no persistence or rwx volumes
replicaCount: 1
service:
  type: ClusterIP
  port: 8055
persistence:
  accessMode: ReadWriteOnce
  storageClass: hcloud-volumes
  size: 10Gi
  enabled: true
  extensions: true
serviceAccount:
  create: false
ingress:
  parentDomain: demo.odit.services
  clusterIssuer: letsencrypt-prod
  domain: ~
auth:
  admin:
    email: demo@odit.services
    password: epiniodemo
  secret: lab
extraEnv: []
livelinessProbe:
  enabled: true
readynessProbe:
  enabled: true
postgres:
  enabled: false
  majorVersion: 16
  persistence:
    size: 10Gi
    storageClass: hcloud-volumes