image:
  pullPolicy: IfNotPresent
  repository: directus/directus
  tag: latest
service:
  type: ClusterIP
  port: 8055
persistence:
  accessMode: ReadWriteOnce
  storageClass: hcloud-volumes
  size: 10Gi
serviceAccount:
  create: false
ingress:
  domain: demo.odit.services
  clusterIssuer: letsencrypt-prod
auth:
  admin:
    email: demo@odit.services
    password: epiniodemo
  secret: lab
extraEnv: []
