apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  commonName: "{{ include "directus.domain" . }}"
  secretName: {{ include "directus.fullname" . }}-tls
  dnsNames:
    - {{ include "directus.domain" . }}
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer