{{- include "validate.values" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if .Values.strategy.rollingUpdate }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default 1 }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "directus.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "directus.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.persistence.enabled}}
          volumeMounts:
            {{- if eq .Values.postgres.enabled false}}
            - name: data
              mountPath: /directus/database
              subPath: database
            {{- end}}
            - name: data
              mountPath: /directus/uploads
              subPath: uploads
            {{- if .Values.persistence.extensions}}
            - name: data
              mountPath: /directus/extensions
              subPath: extensions
            {{- end}}
          {{- end}}
          ports:
            - name: http
              containerPort: 8055
              protocol: TCP
          env:
            - name: PUBLIC_URL
              value: "{{ include "directus.url" .}}"
          {{- if .Values.postgres.enabled }}
            - name: DB_CLIENT
              value: "pg"
            - name: DB_HOST
              value: "{{ include "directus.dbname" . }}-rw"
            - name: DB_PORT
              value: "5432"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: "{{ include "directus.dbname" . }}-app"
                  key: uri
          {{- else}}
            - name: DB_FILENAME
              value: "/directus/database/data.db"
            - name: DB_CLIENT
              value: "sqlite3"
          {{- end}}
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "directus.fullname" . }}
                  key: adminEmail
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "directus.fullname" . }}
                  key: adminPassword
            - name: SECRET
              value: "{{ .Values.auth.secret }}"
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if eq .Values.livelinessProbe.enabled true }}
          livenessProbe:
            httpGet:
              path: /server/ping
              port: http
          {{- end }}
          {{- if eq .Values.readynessProbe.enabled true }}
          readinessProbe:
            httpGet:
              path: /server/ping
              port: http
          {{- end }}
      {{- if .Values.persistence.enabled}}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "directus.fullname" . }}
      {{- end}}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}