apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ include "directus.releasename" . }}.{{ .Values.ingress.domain }}`)
      services:
        - name: {{ include "directus.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: {{ include "directus.fullname" . }}-tls