{{ $s3Server := (lookup "s3.odit.services/v1alpha1" "S3Server" .Values.backup.s3ops.serverRef.namespace .Values.backup.s3ops.serverRef.name) }}
{{- if not $s3Server }}
{{fail "S3 Server not found"}}
{{- end}}

{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "directus.dbname" . }}
spec:
  instances: {{ .Values.postgres.instances }}
  storage:
    size: {{ .Values.postgres.persistence.size }}
    storageClass: {{ .Values.postgres.persistence.storageClass }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: {{ .Values.postgres.majorVersion }}
  {{- if .Values.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: "s3://{{ include "directus.backupbucket.name" . }}/db"
      endpointURL: "http{{if $s3Server.spec.tls }}s{{end}}://{{ $s3Server.spec.endpoint }}"
      s3Credentials:
        accessKeyId:
          name: "{{ include "directus.backupbucket.secret" . }}"
          key: accessKey
        secretAccessKey:
          name: "{{ include "directus.backupbucket.secret" . }}"
          key: secretKey
    retentionPolicy: "30d"
  {{- end}}
{{- end}}