{{- if .Values.postgres.enabled }}
  {{- $s3Server := dict "spec" (dict "endpoint" "mock-endpoint" "tls" false) }}  # Default value for $s3Server

  {{- if .Values.backup.enabled }}
    {{- if .Release.IsInstall }}
      {{- $s3Server = (lookup "s3.odit.services/v1alpha1" "S3Server" .Values.backup.s3ops.serverRef.namespace .Values.backup.s3ops.serverRef.name) }}
      {{- if not $s3Server }}
        {{ fail "S3 Server not found" }}
      {{- end }}
    {{- end }}
  {{- end }}

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "directus.dbname" . }}
spec:
  instances: {{ .Values.postgres.instances }}
  storage:
    size: {{ .Values.postgres.persistence.size }}
    storageClass: {{ .Values.postgres.persistence.storageClass }}
  {{- if .Values.postgres.image }}
  imageName: {{ .Values.postgres.image }}
  {{- end }}
  {{- if .Values.postgres.majorVersion}}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: {{ .Values.postgres.majorVersion }}
  {{- end }}
{{- end }}