---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminEmail: {{ .Values.auth.admin.email }}
  adminPassword: {{ .Values.auth.admin.password }}
  secret: {{ .Values.auth.secret }}
  domain: "{{ include "directus.releasename" . }}.{{ .Values.ingress.domain }}"